name: capstone_catatan_keuangan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.4
  intl: ^0.19.0
  url_launcher: ^6.2.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.5
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets: ['./assets/', ]
